name: ground_flip
description: "GroundFlip"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: 3.22.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  get: ^4.6.6
  flutter_dotenv: ^5.1.0
  location: ^6.0.1
  permission_handler: ^11.3.1
  google_maps_flutter: ^2.6.1
  flutter_config: ^2.0.2
  health: ^10.2.0
  fl_chart: ^0.68.0
  dropdown_button2: ^2.3.9
  pedometer: ^4.0.1
  get_storage: ^2.1.1
  flutter_foreground_task: ^6.5.0
  kakao_flutter_sdk: ^1.9.3
  flutter_secure_storage: ^9.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  sign_in_with_apple: ^6.1.1
  animated_toggle_switch: ^0.8.2
  provider: ^6.1.2
  url_launcher: ^6.3.0
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1
  smooth_page_indicator: ^1.2.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  assets:
    - .env
    - assets/map_style/
    - assets/images/
    - assets/images/permission/
  uses-material-design: true

flutter_native_splash:
  color: "#000000"
  image: "assets/images/ground_flip_app_icon.png"