name: ground_flip
description: "GroundFlip"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: 3.22.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  get: ^4.6.6
  flutter_dotenv: ^5.1.0
  location: ^6.0.1
  permission_handler: ^11.3.1
  google_maps_flutter: ^2.6.1
  flutter_config: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  assets:
    - .env
    - assets/map_style/
  uses-material-design: true

