name: Flutter CI

on:
  pull_request:
    branches:
      - develop*

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set env
        run: |
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml

      - name: Install dependencies
        run: flutter pub get

      - name: Flutter analyze
        run: flutter analyze

      - name: Flutter test
        run: flutter test
